import builtins
from typing import Protocol
from uuid import UUID

from facebook_group_tool.domain.entities.campaign import Campaign
from facebook_group_tool.domain.entities.campaign_target import CampaignTarget


class CampaignRepository(Protocol):
    async def get(self, campaign_id: UUID) -> Campaign | None: ...
    async def save(self, campaign: Campaign) -> Campaign: ...
    async def save_targets(
        self, targets: builtins.list[CampaignTarget]
    ) -> builtins.list[CampaignTarget]: ...
    async def list_targets(self, campaign_id: UUID) -> builtins.list[CampaignTarget]: ...
    async def count_auto_posts_since_midnight(self) -> int: ...
    async def has_running_auto_campaign(self) -> bool: ...
