import builtins
from typing import Protocol
from uuid import UUID

from facebook_group_tool.domain.entities.group import Group


class GroupRepository(Protocol):
    async def get(self, group_id: UUID) -> Group | None: ...
    async def list(self, *, enabled_only: bool = False) -> builtins.list[Group]: ...
    async def save(self, group: Group) -> Group: ...
    async def upsert_many(self, groups: builtins.list[Group]) -> builtins.list[Group]: ...
